export function exportAsPDF(analysisData) {
  const { repository, repoData, analysis } = analysisData;
  const meta = repoData.metadata;

  // Create a printable HTML document
  const printContent = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>RepoIntel Report - ${meta.fullName}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { 
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; 
      color: #1a1a1a; 
      line-height: 1.6;
      padding: 40px;
      max-width: 800px;
      margin: 0 auto;
    }
    h1 { font-size: 28px; margin-bottom: 8px; }
    h2 { font-size: 20px; margin: 32px 0 12px; padding-bottom: 8px; border-bottom: 2px solid #e5e7eb; }
    h3 { font-size: 16px; margin: 16px 0 8px; }
    p { margin-bottom: 8px; color: #4a5568; }
    .header { border-bottom: 3px solid #6C5CE7; padding-bottom: 16px; margin-bottom: 32px; }
    .header .subtitle { color: #6b7280; font-size: 14px; }
    .scores { display: flex; gap: 24px; margin: 16px 0; }
    .score-box { text-align: center; flex: 1; padding: 16px; border: 1px solid #e5e7eb; border-radius: 8px; }
    .score-box .value { font-size: 36px; font-weight: 700; }
    .score-box .label { font-size: 12px; color: #6b7280; text-transform: uppercase; }
    .green { color: #00C896; }
    .yellow { color: #F5A524; }
    .red { color: #FF4D4F; }
    .pills { display: flex; flex-wrap: wrap; gap: 6px; margin: 8px 0; }
    .pill { padding: 2px 10px; border-radius: 999px; font-size: 12px; background: #f3f4f6; border: 1px solid #e5e7eb; }
    ul { margin: 8px 0 8px 20px; }
    li { margin-bottom: 4px; color: #4a5568; }
    .meta { font-size: 12px; color: #9ca3af; margin-top: 32px; padding-top: 16px; border-top: 1px solid #e5e7eb; }
    @media print {
      body { padding: 20px; }
      .no-print { display: none; }
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>📊 ${meta.fullName}</h1>
    <p class="subtitle">${meta.description || 'No description'}</p>
    <p class="subtitle">Generated by RepoIntel — ${new Date().toLocaleDateString()}</p>
  </div>

  <h2>Score Overview</h2>
  <div class="scores">
    <div class="score-box">
      <div class="value ${getColorClass(analysis.scores.quality)}">${analysis.scores.quality}</div>
      <div class="label">Quality</div>
    </div>
    <div class="score-box">
      <div class="value ${getColorClass(analysis.scores.security)}">${analysis.scores.security}</div>
      <div class="label">Security</div>
    </div>
    <div class="score-box">
      <div class="value ${getColorClass(analysis.scores.documentation)}">${analysis.scores.documentation}</div>
      <div class="label">Documentation</div>
    </div>
    <div class="score-box">
      <div class="value ${getColorClass(analysis.scores.maintainability)}">${analysis.scores.maintainability}</div>
      <div class="label">Maintainability</div>
    </div>
  </div>

  <h2>Summary</h2>
  <p>${analysis.summary}</p>

  <h2>Tech Stack</h2>
  ${renderPDFStack('Primary', analysis.techStack?.primary)}
  ${renderPDFStack('Secondary', analysis.techStack?.secondary)}
  ${renderPDFStack('DevOps', analysis.techStack?.devOps)}
  ${renderPDFStack('Testing', analysis.techStack?.testing)}

  <h2>Languages</h2>
  <div class="pills">
    ${Object.entries(repoData.languages).map(([lang, info]) =>
    `<span class="pill">${lang}: ${info.percentage}%</span>`
  ).join('')}
  </div>

  <h2>Architecture</h2>
  <p><strong>Pattern:</strong> ${analysis.architecture?.pattern || 'Unknown'}</p>
  <p>${analysis.architecture?.description || ''}</p>

  <h2>Score Explanations</h2>
  ${analysis.scoreExplanations ? Object.entries(analysis.scoreExplanations).map(([key, val]) =>
    `<h3>${key.charAt(0).toUpperCase() + key.slice(1)}</h3><p>${val}</p>`
  ).join('') : '<p>No explanations available.</p>'}

  <h2>Deep Dive</h2>
  <p>${analysis.deepDive || ''}</p>

  <h2>Key Insight</h2>
  <p><em>${analysis.keyInsight || ''}</em></p>

  <h2>Observations</h2>
  <ul>
    ${(analysis.observations || []).map(o => `<li><strong>${o.title}</strong> [${o.priority || 'Medium'}] — ${o.description || o.content}</li>`).join('')}
  </ul>

  <h2>AI Recommendations</h2>
  <ul>
    ${(analysis.recommendations || []).map(r => `<li><strong>${r.title}</strong> [${r.type}/${r.priority}] — ${r.description}</li>`).join('')}
  </ul>

  <h2>Risks</h2>
  <ul>
    ${(analysis.risks || []).map(r => `<li>${r}</li>`).join('')}
  </ul>

  <h2>Highlights</h2>
  <ul>
    ${(analysis.highlights || []).map(h => `<li>${h}</li>`).join('')}
  </ul>

  <h2>How to Run Locally</h2>
  <ol>
    ${(analysis.runInstructions || []).map(s => `<li>${s.step || ''}${s.command ? ` — <code>${s.command}</code>` : ''}</li>`).join('')}
  </ol>

  <div class="meta">
    Stars: ${meta.stars} | Forks: ${meta.forks} | Issues: ${meta.openIssues} | Files: ${repoData.fileCount}<br>
    License: ${meta.license} | Created: ${new Date(meta.createdAt).toLocaleDateString()}<br>
    Report generated by RepoIntel
  </div>
</body>
</html>`;

  // Open print dialog
  const printWindow = window.open('', '_blank');
  printWindow.document.write(printContent);
  printWindow.document.close();
  setTimeout(() => {
    printWindow.print();
  }, 500);
}

function getColorClass(score) {
  if (score >= 80) return 'green';
  if (score >= 50) return 'yellow';
  return 'red';
}

function renderPDFStack(title, items) {
  if (!items || items.length === 0) return '';
  return `<h3>${title}</h3><div class="pills">${items.map(i => `<span class="pill">${i}</span>`).join('')}</div>`;
}

